remote_theme: pmarsceill/just-the-docs
color_scheme: dark
logo: "/images/feature_bundle_open01.png"

aux_links:
  "GitHub Repo":
    - "//github.com/ctjdr/vscode-apprt-bundles"

aux_links_new_tab: true
